version: "3.5"
services:
  nats:
    image: nats
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks: ["nats"]

  postgres_backend_api:
    image: postgres:12-alpine
    container_name: db_postgres
    env_file: ./deployment/loc.env
    ports:
      - 5432:5432
    networks: ["nats"]

  pgAdmin:
    image: dpage/pgadmin4:4.22
    container_name: pgAdmin
    depends_on:
      - postgres_backend_api
    ports:
      - 16555:80
    environment:
      PGADMIN_DEFAULT_EMAIL: developer@mail.ru
      PGADMIN_DEFAULT_PASSWORD: developer
    logging:
      driver: none

  api:
    container_name: api
    build: 
      context: .
      dockerfile: ./services/Dockerfile.api
    ports:
      - "5000:5000"
    depends_on:
      - nats
    networks: ["nats"]

  store:
    container_name: store
    build: 
      context: .
      dockerfile: ./services/Dockerfile.store
    links:
      - postgres_backend_api
    depends_on:
      - nats
      - postgres_backend_api
    networks:
      - nats

networks:
  nats:
    name: nats
    driver: bridge