version: "3.5"
services:
  nats:
    image: nats
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks: ["nats"]

  postgres_backend_api:
    image: postgres:12-alpine
    container_name: db_postgres
    env_file: ./deployment/loc.env
    ports:
      - 5432:5432

  pgAdmin:
    image: dpage/pgadmin4:4.22
    container_name: pgAdmin
    depends_on:
      - postgres_backend_api
    ports:
      - 16555:80
    environment:
      PGADMIN_DEFAULT_EMAIL: developer@mail.ru
      PGADMIN_DEFAULT_PASSWORD: developer
    logging:
      driver: none


networks:
  nats:
    name: nats

# networks:
#   postgres-base-net:
#     driver: bridge

# services:
#   # backend:
#   #   build: .
#   #   environment:
#   #     - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
#   #     - NODE_ENV=development
#   #     - PORT=8080
#   #   ports:
#   #     - "8080:8080"
#   #     # - "5432:5432"
#   #   volumes:
#   #     - ./:/usr/src/app
#   #   command: npm run start
#   #   depends_on:
#   #     - db
#   #   networks:
#   #     - postgres-base-net

#   # db:
#   #   image: postgres:14.1-alpine
#   #   container_name: 'postgres1'
#   #   restart: always
#   #   # restart: on-failure
#   #   environment:
#   #     - POSTGRES_USER=postgres
#   #     - POSTGRES_PASSWORD=postgres
#   #     - POSTGRES_DB=postgres
#   #   ports:
#   #     - '5432:5432'
#   #   networks:
#   #     - postgres-base-net

#   db:
#     image: postgres:14.1-alpine
#     container_name: 'postgres'
#     restart: always
#     # restart: on-failure
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_DB=postgres
#     ports:
#       - '5432:5432'
#     networks:
#       - postgres-base-net

#   # pgadmin:
#   #   container_name: pgadmin4_container
#   #   image: dpage/pgadmin4
#   #   restart: always
#   #   environment:
#   #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
#   #     PGADMIN_DEFAULT_PASSWORD: root
#   #   ports:
  #     - "5050:80"

#   version: '3.3'
# services:

#   api_server:
#     build: .
#     container_name: server
#     ports:
#       - 8888:8888
#     env_file: ./deployment/loc.env
#     volumes:
#       - .:/app
#     links:
#       - postgres_backend_api
#     depends_on:
#       - postgres_backend_api

#   postgres_backend_api:
#     image: postgres:12-alpine
#     container_name: db_postgres
#     env_file: ./deployment/loc.env
#     ports:
#       - 5432:5432

#   pgAdmin:
#     image: dpage/pgadmin4:4.22
#     container_name: pgAdmin
#     depends_on:
#       - postgres_backend_api
#     ports:
#       - 16555:80
#     environment:
#       PGADMIN_DEFAULT_EMAIL: developer@mail.ru
#       PGADMIN_DEFAULT_PASSWORD: developer
#     logging:
#       driver: none